version: "3"

services:
  server:
    image: spymovil/container_spcommsv3_server:latest
    restart: always 
    ports:
    - "8087:80"

  process:
    image: spymovil/container_spcommsv3_process:latest
    restart: always 

  redis:
    image: redis:7.0.3
    restart: always
    ports:
      - "6380:6379" 
    volumes:
      - ./redis:/data